services:
  - type: web
    name: bayesian-world-cup-prediction
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    buildCommand: pip install -r spaces/requirements.txt
    startCommand: python spaces/app.py
    healthCheckPath: /
